### ISSUE TITLE
 1 sync.go:50] cert-manager/controller/ingress-shim "level"=0 "msg"="not syncing ingress resource as it does not contain a \"cert-manager.io/issuer\" or \"cert-manager.io/cluster-issu er\" annotation" "resource_kind"="Ingress" "resource_name"="http01" "resource_namespace"="argocd"

### ISSUE THREAD

**Issue by thanhpd-teko** [argoproj/argoproj-deployments#3]
Steps:
- Clone project
- Change domain
- Apply deployment
Result: invalid certificate.
The logs of certificate-manager:  1 sync.go:50] cert-manager/controller/ingress-shim "level"=0 "msg"="not syncing ingress resource as it does not contain a \"cert-manager.io/issuer\" or \"cert-manager.io/cluster-issu
er\" annotation" "resource_kind"="Ingress" "resource_name"="http01" "resource_namespace"="argocd"
I guest the problem come from version of certificate-manager. Please help me.

**Comment by jessesuen** [comment]
These instructions should help
https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests
